services:
  # Neo4j baza za FollowerService
  neo4j:
    image: neo4j:5
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7687:7687" # bolt
      - "7474:7474" # http ui
    volumes:
      - neo4j_data:/data
    networks:
      - travel-agency-network
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/127.0.0.1/7474' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12

  # PostgreSQL baza za StakeholdersService
  stakeholders-db:
    image: postgres:15
    container_name: stakeholders-db
    environment:
      POSTGRES_DB: stakeholders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
    ports:
      - "5434:5432"
    volumes:
      - stakeholders_data:/var/lib/postgresql/data
    networks:
      - travel-agency-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stakeholders"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL baza za TourService
  tours-db:
    image: postgres:15
    container_name: tours-db
    environment:
      POSTGRES_DB: tours
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
    ports:
      - "5433:5432"
    volumes:
      - tours_data:/var/lib/postgresql/data
    networks:
      - travel-agency-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tours"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL baza za BlogService
  blog-db:
    image: postgres:15
    container_name: blog-db
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
    ports:
      - "5435:5432"
    volumes:
      - blog_data:/var/lib/postgresql/data
    networks:
      - travel-agency-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blog"]
      interval: 10s
      timeout: 5s
      retries: 5

  # StakeholdersService
  stakeholders-service:
    build:
      context: ./services/stakeholders-service
      dockerfile: Dockerfile
    container_name: stakeholders-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=stakeholders-db;Port=5432;Database=stakeholders;Username=postgres;Password=super
      - JWT_KEY=explorer_secret_key_very_long_and_secure_key_for_production
      - JWT_ISSUER=travel-agency
      - JWT_AUDIENCE=travel-agency-users
    ports:
      - "5001:80"
    depends_on:
      stakeholders-db:
        condition: service_healthy
    networks:
      - travel-agency-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  # TourService
  tour-service:
    build:
      context: ./services/tour-service
      dockerfile: Dockerfile
    container_name: tour-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=tours-db;Port=5432;Database=tours;Username=postgres;Password=super
      - JWT_KEY=explorer_secret_key_very_long_and_secure_key_for_production
      - JWT_ISSUER=travel-agency
      - JWT_AUDIENCE=travel-agency-users
    ports:
      - "5002:80"
    depends_on:
      tours-db:
        condition: service_healthy
    networks:
      - travel-agency-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  # BlogService
  blog-service:
    build:
      context: ./services/blog-service
      dockerfile: Dockerfile
    container_name: blog-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://blog-db:5432/blog
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=super
      - SERVER_PORT=8080
    ports:
      - "5003:8080"
    depends_on:
      blog-db:
        condition: service_healthy
    networks:
      - travel-agency-network
    volumes:
      - blog_uploads:/app/uploads
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Follower microservice (Spring Boot + Neo4j)
  follower-microservice:
    build:
      context: ./services/follower-microservice
      dockerfile: Dockerfile
    container_name: follower-microservice
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=password
      - SERVER_PORT=8081
    ports:
      - "5004:8081"
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - travel-agency-network
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/127.0.0.1/8081' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10

  # API Gateway
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - JWT_KEY=explorer_secret_key_very_long_and_secure_key_for_production
      - JWT_ISSUER=travel-agency
      - JWT_AUDIENCE=travel-agency-users
      - STAKEHOLDERS_SERVICE_URL=http://stakeholders-service:80
      - TOUR_SERVICE_URL=http://tour-service:80
      - BLOG_SERVICE_URL=http://blog-service:8080
      - FOLLOWER_SERVICE_URL=http://follower-microservice:8081
    ports:
      - "5000:80"
    depends_on:
      - stakeholders-service
      - tour-service
      - blog-service
      - follower-microservice
    networks:
      - travel-agency-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  stakeholders_data:
  tours_data:
  blog_data:
  blog_uploads:
  neo4j_data:

networks:
  travel-agency-network:
    driver: bridge